#!/usr/bin/env python3
"""
Script Name: calc_promoter_methylation.py
Description: Calculates statistics (Mean Methylation, CpG Count) per promoter/gene.
             
Input Requirement:
    A tab-separated file generated by intersecting Promoters/Genes with a Methylation BedGraph.
    Expected Columns (10 total):
    1-6: Promoter info (Chr, Start, End, GeneID, Score, Strand)
    7-10: Methylation info (Chr, Start, End, MethValue)
    
    This is typically generated via: 
    bedtools intersect -a promoters.bed -b methylation.bedgraph -wa -wb > input.tsv

Author: Paolo Callipo
Date: 2025
Dependencies: pandas
"""

import sys
import argparse
import os
import pandas as pd

def process_methylation(input_file, output_file):
    print(f"Loading data from {input_file}...")

    # Define column names based on bedtools intersect -wa -wb output
    col_names = [
        "promoter_chr", "promoter_start", "promoter_end", "GeneID",
        "promoter_score", "promoter_strand",
        "meth_chr", "meth_start", "meth_end", "Methylation"
    ]

    try:
        # Read the file using pandas
        # low_memory=False handles mixed types if large file
        data = pd.read_csv(input_file, sep='\t', header=None, names=col_names)
        
        if data.empty:
            print("Error: Input file is empty.")
            sys.exit(1)

    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    print("Calculating statistics per promoter...")

    # Group by GeneID
    # 1. Mean_Meth: Average of the 'Methylation' column
    # 2. CpG_Count: Count of rows (sites) per GeneID
    summary = data.groupby('GeneID').agg(
        Mean_Meth=('Methylation', 'mean'),
        CpG_Count=('Methylation', 'size')
    ).reset_index()

    # Round methylation to 2 decimal places
    summary['Mean_Meth'] = summary['Mean_Meth'].round(2)

    # Save to file
    try:
        summary.to_csv(output_file, sep='\t', index=False)
        print(f"\n--- Analysis Complete ---")
        print(f"Processed {len(summary)} unique promoters.")
        print(f"Summary table saved to: {output_file}")
    except PermissionError:
        print(f"Error: Could not write to '{output_file}'. Permission denied.")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(
        description="Calculate mean methylation per promoter from bedtools intersect output.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument('input_file', help="Input TSV file (bedtools intersect -wa -wb output).")
    parser.add_argument('--output', default="all_promoter_stats.tsv", help="Output filename.")
    
    args = parser.parse_args()

    process_methylation(args.input_file, args.output)

if __name__ == "__main__":
    main()
